#!/bin/sh

unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS

# Настройка Xresources
xrdb $HOME/.Xresources
xsetroot -solid grey

/etc/X11/Xsession
gnome-session &

dbus-launch --exit-with-session 
